# Generated by Django 2.2 on 2020-06-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Normal'), (9, 'Admin')], default=0),
        ),
    ]
