# Generated by Django 2.2 on 2020-05-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_auto_20200528_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
