# Generated by Django 2.2 on 2020-06-15 21:12

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[login.models.name_validator])),
                ('last_name', models.CharField(max_length=255, validators=[login.models.name_validator])),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255, validators=[login.models.password_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatede_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
