# Generated by Django 2.2 on 2020-06-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
