# Generated by Django 2.2 on 2020-06-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
